### ISSUE TITLE
Wavy bubbly background

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/scambi.org#27]
Use an SVG within a `::before` attached to body, containing a wavy figure.

```scss
body {
  background: #0000;
  &::before {
    z-index: -1;
    content: 'svg bla bla';
  }
}
```
